name: CI/CD hdev_client to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 CheckOut
        uses: actions/checkout@v3
      
      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAZKP7ENHO4ETWFLUX
          aws-secret-access-key: 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
          aws-region: ap-northeast-2
      
      - name: 리액트 빌드
        run: |
          npm install
          npm run build

      - name: 빌드한 파일 S3에 업로드
        run: aws s3 sync build/ s3://itstudyfront
        env:
          AWS_ACCESS_KEY_ID: AKIAZKP7ENHO4ETWFLUX
          AWS_SECRET_ACCESS_KEY: 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



      